language: objective-c
script: "bash build.sh"
compiler:
  - gcc
branches:
  only:
    - master
notifications:
  email:
    - andrew@andrewschaaf.com

# language: c
# script: "bash build.sh"
# compiler:
#   - clang
#   - gcc
