language: objective-c
script: "env CC=gcc bash build.sh && cd mac-show-ppms && xcodebuild"
branches:
  only:
    - master
notifications:
  email:
    - andrew@andrewschaaf.com

# language: c
# script: "bash build.sh"
# compiler:
#   - clang
#   - gcc
